# Generated by Django 3.1.5 on 2021-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_watchtw'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchTWchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('watch', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='Watchchart',
        ),
        migrations.RenameField(
            model_name='watchchart',
            old_name='name',
            new_name='watch',
        ),
        migrations.DeleteModel(
            name='StoreIncome',
        ),
    ]
